# Automatically created from terraform data on 

all:
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_become: true
    ansible_ssh_private_key_file: snehalkey_ubuntu 20.04


zookeeper:
  hosts:
    ip-172-32-53-10.us-west-2.compute.internal:
    ip-172-32-74-35.us-west-2.compute.internal:
    ip-172-32-85-127.us-west-2.compute.internal:
    
kafka_broker:
  hosts:
    ip-172-32-60-251.us-west-2.compute.internal:
    ip-172-32-65-212.us-west-2.compute.internal:
    ip-172-32-89-24.us-west-2.compute.internal:
    #ip-172-32-55-217.us-west-2.compute.internal:
    

schema_registry:
  hosts:
    ip-172-32-61-146.us-west-2.compute.internal:
    ip-172-32-79-215.us-west-2.compute.internal:
    

kafka_rest:
  hosts:
    

ksql:
  hosts:
    ip-172-32-62-19.us-west-2.compute.internal:
   # ip-172-32-73-96.us-west-2.compute.internal:
    

kafka_connect:
  hosts:
    ip-172-32-57-162.us-west-2.compute.internal:
    ip-172-32-79-104.us-west-2.compute.internal:
    

control_center:
  hosts:
    ip-172-32-55-255.us-west-2.compute.internal:
    
